### ISSUE TITLE
Identification et entité

### ISSUE THREAD

**Issue by azriel68** [azriel68/AToMicERP#10]
Dans le cadre du développement et du mode transverse lié au droit, je crois que l'entité choisie au login devient inutile. Puisque le but et de voir par exemple toutes les companies sur lesquelles on à le droit de vision, alors le choix d'entité type dolibarr devient vraisemblablement fortuit et devrait être reporté sur la création des documents.

Par exemple création Devis/Propal : 
1/ Ai-je le droit de créer un Devis dans une entité oui/non
2/ Si oui, est-ce 1 ou n entité
3/ Si oui ajout du choix de l'entité sous laquelle créer le document

Cela je pense peut simplifier énormément certain process

A rediscuter devant le whiteboard stylo à la main

Si vous voyez des contre évident et rédibitoire, mettre en com. De toute façon aucun dev dans ce sens ne sera entamé avant confrontation

**Comment by atm-maxime** [comment]
J'ai commencé à bosser sur les dictionnaires et la conf, et ces deux notions sont liées à l'entité.
Exemple l'entité 1 n'aura pas le même masque de numérotation des devis que l'entité 2 (conf), et la liste des conditions de règlement (dictionnaire) ne sera pas la même.
Il faudra donc penser à recharger ces deux notions (dict et conf) lors de la sélection de l'entité dans laquelle on créé le document

**Comment by azriel68** [comment]
On est d'accord pour virer l'entité à l'identification
