### ISSUE TITLE
Numbering function

### ISSUE THREAD

**Issue by atm-maxime** [azriel68/AToMicERP#8]
Create a numbering function that will work accross modules by passing the classname, the mask to use

**Comment by atm-maxime** [comment]
Numbering works by setting conf in the module, e.g. 

@$conf->autoref->TCompany = array(
    array('field' => 'customerRef', 'mask' => 'CL{yy}{0000}', 'dateField' => 'dt_cre')
    ,array('field' => 'supplierRef', 'mask' => 'FO{yy}{0000}', 'dateField' => 'dt_cre')
);

Reset the counter every time the date in the mask changes (allow yy, yyyy, mm and dd)

**Comment by atm-maxime** [comment]
Added a TConf class that will allow to define the user conf, and tested with the numbering.
Numbering has been moved to the object save function.

**Comment by azriel68** [comment]
Numbering has been moved to trigger on object save function
